### ISSUE TITLE
Error while setting up smartir platform for climate

### ISSUE THREAD

**Issue by NooB-Noob420** [litinoveweedle/SmartIR#113]
Home Assistant version: 2024.8.2
OS: x86-64 - HP Laptop 
OS version: 13.1
SmartIR version: 1.18.0

SmartIR configuration: 
on esphome IR reciver/transmitter - tried 2 different transmitters Esp-01 from AliExpress and Tuya flashed with ESPhome
yaml:
esphome:
  name: my_espir
  platform: ESP8266
  board: esp8285
    
logger:
  level: DEBUG

api...
  services:
    - service: send_raw_command
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return command;'
            carrier_frequency: 38000

HA configuration.yaml :

climate:
  - platform: smartir
    name: Office AC
    unique_id: office_ac
    device_code: 1623
    controller_data:
      controller_type: ESPHome
      esphome_service: my_espir_send_raw_command
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power
  - platform: smartir
    name: bedroom AC
    unique_id: bedroom_ac
    device_code: 1340
    controller_data:
      controller_type: ESPHome
      esphome_service: my_espir_send_raw_command
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power

Got this Log Error:
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:364
integration: Climate (documentation, issues)
First occurred: 22:10:53 (2 occurrences)
Last logged: 22:10:53

Error while setting up smartir platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/smartir/climate.py", line 90, in async_setup_platform
    async_add_entities([SmartIRClimate(hass, config, device_data)])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartir/climate.py", line 224, in __init__
    self._controller = get_controller(
                       ^^^^^^^^^^^^^^^
  File "/config/custom_components/smartir/controller.py", line 49, in get_controller
    raise Exception(
Exception: Configured controller is not supported by the device data file.

 ----

Did I do something wrong setting it? I followed this thread: 
https://community.home-assistant.io/t/smartir-control-your-climate-tv-and-fan-devices-via-ir-rf-controllers/100798/1511

**Comment by NooB-Noob420** [comment]
Thank you for your quick response and apologies for my ignorance!! 
honestly I couldn't figure out completely how the integration works, It did not creates an entity for climate. 
I guess by your answer it is because a device file for the controller type (esphome right?) is missing, can you please direct me to the right resource where I can learn what to do? 
honest apologies I have been sitting days and nights going throw forums and documentations trying to figure out how to set up IR remotes in general and climate as well.. 
Thank you for your time and efforts making this Integration work!
