### ISSUE TITLE
Attempting to write to MQTT server - errors coming

### ISSUE THREAD

**Issue by MikeatLorne** [litinoveweedle/SmartIR#36]
I am not sure if this is a SmartIR issue or it is me causing it.  I'd appreciate a pointer on what is wrong.  with thanks

**Home Assistant version**
2024.6.3
**SmartIR version**
1.17.16
**SmartIR configuration**

climate:
  - platform: smartir
    name: l1_rumpus_ac
    unique_id: l1_rumpus_aircon
    device_code: 1101
    controller_data: homeassistant/l1_rumpus_ac
```

**Describe the bug**

I am attempting to write SmartIR to an MQTT topic. (in order to drive a GlobalCache IP2IR to control my Daikin Splits)  I have the topic appearing in MQTT explorer but SmartIR is not writing to it.

**Debug log**
This error originated from a custom integration.

Logger: custom_components.smartir.climate
Source: custom_components/smartir/climate.py:591
integration: smartir (documentation, issues)
First occurred: 11:08:05 (1 occurrences)
Last logged: 11:08:05

not a valid value for dictionary value @ data['entity_id']
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 591, in _send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 117, in send
    await self.hass.services.async_call("remote", "send_command", service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 2706, in async_call
    processed_data: dict[str, Any] = handler.schema(service_data)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.12/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: not a valid value for dictionary value @ data['entity_id']
```text

Add your logs here.

 with thanks

**Comment by MikeatLorne** [comment]
I am asking the wrong question - will raise a new one
