### ISSUE TITLE
Climate code "3040" for Vitoclima 300-S not working

### ISSUE THREAD

**Issue by revoked9767** [litinoveweedle/SmartIR#76]
**Home Assistant version**
2024.7.2
**SmartIR version**
1.17.16

Add SmartIR relevant part of HA configuration.yaml  formatted as a code here

using ESPHome integration
climate:
  - platform: smartir
    name: Office AC2
    unique_id: office_ac2
    device_code: 3040
    controller_data: esp32ir_send_raw_command

**Describe the bug**
when using this specific device code the card in home assistant does not respond and update to given commands, it also does not interact with ESPHome, tested it with another code and it works as intended
 
**To Reproduce**
1. Go to 'Home assistant thermostat card'
2. Click on 'any button, example: change from off to heat'
3. See error (no output in card and on esphome log)

**Debug log**
```
`2024-07-15 11:40:17.594 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-07-15 11:40:17.595 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartir which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-07-15 11:40:18.537 ERROR (SyncWorker_5) [homeassistant.components.influxdb] InfluxDB database is not accessible due to '401: {"code":"unauthorized","message":"Unauthorized"}'. Please check that the database, username and password are correct and that the specified user has the correct permissions set. Retrying in 60 seconds.
2024-07-15 11:40:19.001 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/frontend", "/config/custom_components/hacs/hacs_frontend_experimental", False)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 49: hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
2024-07-15 11:40:19.004 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/iconset.js", "/config/custom_components/hacs/iconset.js", True)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 57: hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
2024-07-15 11:40:19.005 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-07-15 11:40:19.476 ERROR (MainThread) [homeassistant.components.automation] Automation with alias 'CAMERA_FREDDO' failed to setup actions and has been disabled: Unknown entity '9997b7d8ae0731b7b531002a558d161f'
2024-07-15 11:40:19.607 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-07-15 11:40:22.417 ERROR (MainThread) [custom_components.smartir.climate] Service remote.send_command not found
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 591, in _send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 117, in send
    await self.hass.services.async_call("remote", "send_command", service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 2664, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Service remote.send_command not found
2024-07-15 11:40:22.527 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esphome-web-a331c0 @ 192.168.1.159: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.1.159', port=6053))]: [Errno 113] Connect call failed ('192.168.1.159', 6053) (SocketAPIError)
2024-07-15 11:40:23.670 ERROR (MainThread) [custom_components.smartir.climate] Service remote.send_command not found
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 524, in _send_command
    await self._controller.send(self._commands["off"])
  File "/config/custom_components/smartir/controller.py", line 117, in send
    await self.hass.services.async_call("remote", "send_command", service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 2664, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Service remote.send_command not found
2024-07-15 11:40:24.259 ERROR (MainThread) [custom_components.smartir.climate] Service remote.send_command not found
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 591, in _send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 117, in send
    await self.hass.services.async_call("remote", "send_command", service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 2664, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Service remote.send_command not found
2024-07-15 11:40:24.679 ERROR (MainThread) [custom_components.smartir.climate] Service remote.send_command not found
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 591, in _send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 117, in send
    await self.hass.services.async_call("remote", "send_command", service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 2664, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Service remote.send_command not found
2024-07-15 11:40:26.227 ERROR (MainThread) [custom_components.smartir.climate] Service remote.send_command not found
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 591, in _send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 117, in send
    await self.hass.services.async_call("remote", "send_command", service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 2664, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Service remote.send_command not found
2024-07-15 11:40:26.605 ERROR (MainThread) [custom_components.smartir.climate] Service remote.send_command not found
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 591, in _send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 117, in send
    await self.hass.services.async_call("remote", "send_command", service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 2664, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Service remote.send_command not found
2024-07-15 11:40:27.783 ERROR (MainThread) [custom_components.smartir.climate] Service remote.send_command not found
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 591, in _send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 117, in send
    await self.hass.services.async_call("remote", "send_command", service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 2664, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Service remote.send_command not found
2024-07-15 11:40:28.208 ERROR (MainThread) [custom_components.smartir.climate] Service remote.send_command not found
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 591, in _send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 117, in send
    await self.hass.services.async_call("remote", "send_command", service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 2664, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Service remote.send_command not found
2024-07-15 11:43:38.622 ERROR (MainThread) [custom_components.smartir.climate] Service remote.send_command not found
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 591, in _send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 117, in send
    await self.hass.services.async_call("remote", "send_command", service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 2664, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Service remote.send_command not found
`
```

**Comment by litinoveweedle** [comment]
Your controller esp32ir_send_raw_command doesn't support service remote.send_command. Please check if you are able to send command from the HA GUI (Developer Tools -> Services). This is not a bug of this integration.
